// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4EafR_nyu36DVec7L4R-fsEdqm1tRD14',
    appId: '1:704231007249:web:f2ec5c95f6211942e0fdb0',
    messagingSenderId: '704231007249',
    projectId: 'work-2d06f',
    authDomain: 'work-2d06f.firebaseapp.com',
    storageBucket: 'work-2d06f.appspot.com',
    measurementId: 'G-CC4M0B3HYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9dYhBgNXmZJzFLmwsxkEBKwWdYq4FLZs',
    appId: '1:704231007249:android:ff67dabc37330230e0fdb0',
    messagingSenderId: '704231007249',
    projectId: 'work-2d06f',
    storageBucket: 'work-2d06f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS4GiedlJnl3DSN4eA3vieO3Uvk1aZUtg',
    appId: '1:704231007249:ios:9c3378ed7ec56e8de0fdb0',
    messagingSenderId: '704231007249',
    projectId: 'work-2d06f',
    storageBucket: 'work-2d06f.appspot.com',
    iosBundleId: 'com.puma.firstfiremusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS4GiedlJnl3DSN4eA3vieO3Uvk1aZUtg',
    appId: '1:704231007249:ios:9c3378ed7ec56e8de0fdb0',
    messagingSenderId: '704231007249',
    projectId: 'work-2d06f',
    storageBucket: 'work-2d06f.appspot.com',
    iosBundleId: 'com.puma.firstfiremusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4EafR_nyu36DVec7L4R-fsEdqm1tRD14',
    appId: '1:704231007249:web:2f92e6ab58652419e0fdb0',
    messagingSenderId: '704231007249',
    projectId: 'work-2d06f',
    authDomain: 'work-2d06f.firebaseapp.com',
    storageBucket: 'work-2d06f.appspot.com',
    measurementId: 'G-JS3535ND0T',
  );
}
